# Generated by Django 4.2.2 on 2023-07-24 16:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('investment_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='investment_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
