# Generated by Django 4.2.2 on 2023-08-02 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment_management', '0003_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='owners',
            field=models.ManyToManyField(to='investment_management.userprofile'),
        ),
    ]
