# Generated by Django 4.2.2 on 2023-08-02 13:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('investment_management', '0004_investment_owners'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='owners',
            field=models.ManyToManyField(related_name='invested_investments', to=settings.AUTH_USER_MODEL),
        ),
    ]
