# Generated by Django 4.2.2 on 2023-08-08 10:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('investment_management', '0005_alter_investment_owners'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='added_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('ledger_fees', 'Ledger Fees'), ('interest', 'Interest'), ('bank_charges', 'Bank Charges'), ('others', 'Others')], max_length=16),
        ),
    ]
