# Generated by Django 4.2.2 on 2023-08-08 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment_management', '0006_transaction_added_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='next_repayment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='investment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
