# Generated by Django 4.2.4 on 2023-09-14 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investment_management', '0010_investment_investment_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investment',
            name='owners',
        ),
        migrations.AlterField(
            model_name='investment',
            name='investment_group',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='investment_management.investmentgroup'),
            preserve_default=False,
        ),
    ]
