# Generated by Django 4.2.4 on 2023-09-14 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment_management', '0012_remove_investment_investment_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='amount_invested',
            field=models.DecimalField(decimal_places=2, max_digits=1000),
        ),
        migrations.AlterField(
            model_name='investment',
            name='daily_interest',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=1000),
        ),
        migrations.AlterField(
            model_name='investment',
            name='deposits',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=1000),
        ),
        migrations.AlterField(
            model_name='investment',
            name='principal',
            field=models.DecimalField(decimal_places=2, max_digits=1000),
        ),
        migrations.AlterField(
            model_name='investment',
            name='withdrawals',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=1000),
        ),
    ]
