# Generated by Django 4.2.4 on 2023-09-16 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment_management', '0013_alter_investment_amount_invested_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10000),
        ),
    ]
