# Generated by Django 4.2.4 on 2023-09-26 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment_management', '0014_alter_transaction_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='transaction_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='investment',
            name='interest_rate',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='investment',
            name='investment_name',
            field=models.CharField(max_length=1000),
        ),
    ]
